homepage: "http://projects.spring.io/spring-shell/"
language: jvm
main_repo: "https://github.com/spring-projects/spring-shell.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "jacek.trossen@code-intelligence.com"
  - "peter.samarin@code-intelligence.com"